chore(docs): update mockFunction API documentation
hulu/roca pull request #82
Opened 2021-03-29 21:22 UTC by lkipke

Closes #81

2021-03-30 20:21 UTC, sjbarag requested changes
Looks like a little copy-spaghetti spilled onto your keyboard here 😛 

Looks great once we get the docs for `mock.mockReturnValue(value)` fixed!

2021-03-30 20:21 UTC, sjbarag commented on docs/api/reference/mocks.md
> +    return "myFunc: " requiredArg
I think you'll need a `+` between these values 😉 

```suggestion
    return "myFunc: " + requiredArg
```

2021-03-30 20:21 UTC, sjbarag commented on docs/api/reference/mocks.md
> +------------
🤔 these look like copy-pasta errors?

2021-03-30 23:09 UTC, lkipke commented on docs/api/reference/mocks.md
> +------------
🤦

2021-03-30 23:21 UTC, lkipke commented on docs/guides/testing-functions.md
> +        <!-- Field that gets modified as a side-effect of the `foo` function -->
This fixes a different copy-lasagna error from #85... turns out when i write documentation i need to be a little more careful 😅

2021-04-01 16:44 UTC, sjbarag approved these changes
Looks like the copy-farfalle is all gone — thanks for the quick cleanup!

2021-04-01 16:45 UTC, merged